### ISSUE TITLE
Why the remove of device/sample when required by target?

### ISSUE THREAD

**Issue by divadsn** [PixelExperience-P/manifest#1]
Hey,

I was recently building PixelExperience P for my Honor View 10 using this manifest, 
but the build failed before start due to a missing dependency:
`ninja: error: 'device/sample/etc/apns-full-conf.xml', needed by '/home/divad_nnamtdeis/jenkins/out/target/product/berkeley/system/etc/apns-conf.xml', miss
ing and no known rule to make it`

After a research I figured out that the `device/sample` is missing, while the `build/target/product/full_base_telephony.mk` is requiring a file from that repo.

Now I see that it is being removed by the manifest here, but why?

**Comment by celtare21** [comment]
It's required only for your phone. You can track it yourself

**Comment by jhenrique09** [comment]
https://github.com/PixelExperience-P/build/search?q=apn&type=Commits
